# Generated by Django 2.0.2 on 2018-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='headboards')),
                ('album', models.ForeignKey(on_delete=False, to='albums.Album')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
