# Generated by Django 2.0.2 on 2018-02-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['name']},
        ),
    ]
